---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bosh/os-image-stemcell-builder

inputs:
  - name: bosh-linux-stemcell-builder
  - name: ubuntu-trusty-tarball
  - name: centos-7-tarball

outputs:
  - name: bosh-linux-stemcell-builder-push

run:
  path: bosh-linux-stemcell-builder/ci/os-images/tasks/bump-os-image.sh
