platform: linux

image_resource:
  type: docker-image
  source:
    repository: bosh/main-base

params:
  BRANCH: ~
  PROJECT_ID: ~
  TOKEN: ~

inputs:
  - name: bosh-linux-stemcell-builder

run:
  path: bosh-linux-stemcell-builder/ci/tasks/create-story.sh
